"""initial schema

Revision ID: ec1b3baa9b4e
Revises:
Create Date: 2026-07-27

Hand-written rather than autogenerated: this is the project's first
migration, created against an empty database (no prior revision to diff
against), so it mirrors app/models/ 1:1 instead of an autogenerate diff.
Matches spec.md section 5.2, generalized for multi-country per
app/core/countries.py: `clients.country_code` selects the CountryRules used
for that client, and `twilio_numbers.phone_e164` uses the generic E.164
CHECK (not a PL-only `+48` pattern) so a future country's numbers aren't
rejected at the DB layer.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ec1b3baa9b4e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext"')

    op.create_table(
        "clients",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("owner_phone_e164", sa.String(16), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="trial"),
        sa.Column("country_code", sa.String(2), nullable=False, server_default="PL"),
        sa.Column("daily_sms_limit", sa.Integer(), nullable=False, server_default="100"),
        sa.Column("log_retention_days", sa.Integer(), nullable=False, server_default="90"),
        sa.Column(
            "anonymization_salt",
            sa.String(),
            nullable=False,
            server_default=sa.text("encode(gen_random_bytes(16), 'hex')"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("email", name="uq_clients_email"),
        sa.CheckConstraint(
            "status IN ('trial', 'active', 'suspended', 'cancelled')", name="ck_clients_status"
        ),
        sa.CheckConstraint(
            r"owner_phone_e164 ~ '^\+[1-9][0-9]{6,14}$'", name="ck_clients_owner_phone"
        ),
        sa.CheckConstraint("country_code ~ '^[A-Z]{2}$'", name="ck_clients_country_code"),
    )

    op.create_table(
        "twilio_numbers",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clients.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("phone_e164", sa.String(16), nullable=False),
        sa.Column("twilio_sid", sa.String(64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("phone_e164", name="uq_twilio_numbers_phone"),
        sa.UniqueConstraint("twilio_sid", name="uq_twilio_numbers_sid"),
        sa.CheckConstraint(r"phone_e164 ~ '^\+[1-9][0-9]{6,14}$'", name="ck_twilio_numbers_phone"),
    )
    op.create_index(
        "idx_twilio_numbers_lookup",
        "twilio_numbers",
        ["phone_e164"],
        postgresql_where=sa.text("is_active"),
    )

    op.create_table(
        "ai_prompts",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clients.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("fallback_message", sa.Text(), nullable=False),
        sa.Column(
            "allow_diacritics", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("max_sms_segments", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint("max_sms_segments BETWEEN 1 AND 3", name="ck_ai_prompts_max_segments"),
    )
    op.create_index(
        "uq_ai_prompts_active",
        "ai_prompts",
        ["client_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )

    op.create_table(
        "call_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("call_sid", sa.String(64), nullable=False),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clients.id"),
            nullable=True,
        ),
        sa.Column(
            "twilio_number_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("twilio_numbers.id"),
            nullable=True,
        ),
        sa.Column("caller_e164", sa.String(16), nullable=True),
        sa.Column("caller_hash", sa.String(64), nullable=True),
        sa.Column("forwarded_from", sa.String(16), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="received"),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("call_sid", name="uq_call_events_call_sid"),
        sa.CheckConstraint(
            "status IN ("
            "'received','no_tenant','client_suspended','anonymous','invalid_number',"
            "'loop_detected','opted_out','non_mobile','deduplicated','limit_exceeded',"
            "'sms_queued','sms_sent','sms_failed')",
            name="ck_call_events_status",
        ),
    )
    op.create_index(
        "idx_call_events_client_time", "call_events", ["client_id", sa.text("received_at DESC")]
    )
    op.create_index(
        "idx_call_events_dedup",
        "call_events",
        ["client_id", "caller_e164", sa.text("received_at DESC")],
        postgresql_where=sa.text("caller_e164 IS NOT NULL"),
    )

    op.create_table(
        "sms_messages",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "call_event_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("call_events.id"),
            nullable=False,
        ),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clients.id"),
            nullable=False,
        ),
        sa.Column("message_sid", sa.String(64), nullable=True),
        sa.Column("to_e164", sa.String(16), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("encoding", sa.String(), nullable=False, server_default="gsm7"),
        sa.Column("segments", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("is_fallback", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("status", sa.String(), nullable=False, server_default="queued"),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("price_usd", sa.Numeric(8, 5), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("message_sid", name="uq_sms_messages_sid"),
        sa.CheckConstraint("encoding IN ('gsm7', 'ucs2')", name="ck_sms_messages_encoding"),
        sa.CheckConstraint(
            "status IN ('queued', 'sent', 'delivered', 'undelivered', 'failed')",
            name="ck_sms_messages_status",
        ),
    )
    op.create_index(
        "idx_sms_messages_client_time", "sms_messages", ["client_id", sa.text("created_at DESC")]
    )

    op.create_table(
        "opt_outs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clients.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("phone_e164", sa.String(16), nullable=False),
        sa.Column("source", sa.String(), nullable=False, server_default="sms_stop"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("client_id", "phone_e164", name="uq_opt_outs_client_phone"),
        sa.CheckConstraint(
            "source IN ('sms_stop', 'manual', 'twilio_21610')", name="ck_opt_outs_source"
        ),
    )


def downgrade() -> None:
    op.drop_table("opt_outs")
    op.drop_index("idx_sms_messages_client_time", table_name="sms_messages")
    op.drop_table("sms_messages")
    op.drop_index("idx_call_events_dedup", table_name="call_events")
    op.drop_index("idx_call_events_client_time", table_name="call_events")
    op.drop_table("call_events")
    op.drop_index("uq_ai_prompts_active", table_name="ai_prompts")
    op.drop_table("ai_prompts")
    op.drop_index("idx_twilio_numbers_lookup", table_name="twilio_numbers")
    op.drop_table("twilio_numbers")
    op.drop_table("clients")
